### ISSUE TITLE
about  the source of some parameters of the discretization dependent scaling of A matrix

### ISSUE THREAD

**Issue by chenyuege** [Computational-Periscopy/Ordinary-Camera#4]
sr = 1.1406e+04/(Ndiscr_mon^2)*prod(subblocksperaxis)*0.9; 
sg = 1.3594e+04/(Ndiscr_mon^2)*prod(subblocksperaxis)*0.98; 
 sb = 1.9063e+04/(Ndiscr_mon^2)*prod(subblocksperaxis)*1.04;
How do these parameters （1.1406e+04,1.3594e+04,1.9063e+04 and so on）come from?

**Comment by Computational-Periscopy** [comment]
These parameters are selected such that the scaling of the A matrix roughly results in an image reconstruction in the 0-1 range. The  (Ndiscr_mon^2)*prod(subblocksperaxis) terms approximately account for the scaling due to the discretization and number of blocks, so that this value does not need to be tuned if those values are changed.

**Comment by chenyuege** [comment]
thank you
